server:
  port: 8090

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/se?useUnicode=true&characterEncoding=utf-8&useSSL=false&severTimezone=GM%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: seuser
    password: "selocalhost"
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
#  aop:
#    proxy-target-class: false
logging:
  level:
    com.example.wms.mapper: debug
jwt:
  secret-key: "KgszcQOvIT9j04Ri6Mn7Eo2H1CX8cXxquswNHDiyc34="

alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI5tHd81k9sjZ4AtV5RtZq
  access-key-secret: zysTqJGfyjfCTtKHaSAyWL5Da9K8qz
  bucket-name: sky-aliyunitcast

cors:
  domain: "localhost,8.138.27.126"
