server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://120.77.79.53:3306/cs304?useUnicode=true&characterEncoding=utf-8&useSSL=false&severTimezone=GM%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    com.example.wms.mapper: debug
