server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://120.77.79.53:3306/cs304?useUnicode=true&characterEncoding=utf-8&useSSL=false&severTimezone=GM%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hailong
    password: "fnv7ZFe26h69r7VCwMj9"
logging:
  level:
    com.example.wms.mapper: debug
jwt:
  secret-key: "KgszcQOvIT9j04Ri6Mn7Eo2H1CX8cXxquswNHDiyc34="

alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI5tHd81k9sjZ4AtV5RtZq
  access-key-secret: zysTqJGfyjfCTtKHaSAyWL5Da9K8qz
  bucket-name: sky-aliyunitcast

cors:
  domain: "120.77.79.53"