name: Test and Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Generate coverage report
      run: mvn jacoco:report
