#AI-generated-content * tool: ChatGPT
#version: 3.5
#usage: I used the prompt "怎么使用github actions实现自动化测试和生成测试覆盖率报告", and use the code from its response after some modification
name: Test and Coverage

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: 'jdk'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean package --file cs304/pom.xml

      - name: Prepare JaCoCo Agent
        run: mvn org.jacoco:jacoco-maven-plugin:0.8.9:prepare-agent -f cs304/pom.xml

      - name: Run tests
        run: mvn test -f cs304/pom.xml

      - name: Generate coverage report
        run: mvn org.jacoco:jacoco-maven-plugin:0.8.9:report -f cs304/pom.xml

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cs304/target/site/jacoco
